/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Keberangkatan;
import entity.Paket;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import repository.KeberangkatanRepository;
import repository.PaketRepository;
import service.ComboItem;
import util.DateUtil;

/**
 *
 * @author adzaz
 */
public class DialogTambahKeberangkatan extends Dialog {
    KeberangkatanRepository keberangkatanRepo = new KeberangkatanRepository();
    PaketRepository paketRepo = new PaketRepository();
    private List<Paket> pakets = new ArrayList<>();
    private String menu = "";
    DateUtil dateUtil = new DateUtil();
    /**
     * Creates new form DialogTambahKeberangkatan
     */
    public DialogTambahKeberangkatan(JFrame fram) {
        super(fram);
        initComponents();
    }
    
    private void fillComboBox(){
  
   
        if(menu.equals("")){
            pakets = paketRepo.get();
        }else{
            pakets = paketRepo.getByMenu(menu);
        }
        int a = pakets.size();
        for (int i = 0; i < a; i++) {
            Paket paket = pakets.get(i);
            cmbPaket.addItem(paket.getId()+", "+paket.getNama());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new com.raven.datechooser.DateChooser();
        txtDate = new javax.swing.JTextField();
        btnDate = new javax.swing.JLabel();
        cmbPaket = new javax.swing.JComboBox<>();
        cmbMenu = new javax.swing.JComboBox<>();
        lblDesc = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblMinimDp = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        date.setDateFormat("yyyy-MM-dd");
        date.setTextRefernce(txtDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 145, 180, 40));

        btnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateMouseClicked(evt);
            }
        });
        getContentPane().add(btnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, 50));

        cmbPaket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---pilih---" }));
        cmbPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbPaketMouseClicked(evt);
            }
        });
        cmbPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaketActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 142, 240, 45));

        cmbMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--pilih--", "umrah", "haji", "wisata halal" }));
        cmbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMenuActionPerformed(evt);
            }
        });
        getContentPane().add(cmbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 142, 230, 45));

        lblDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 470, 40));

        lblDiskon.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 470, 50));

        lblMinimDp.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblMinimDp.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblMinimDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 343, 470, 50));

        lblHarga.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 295, 470, 50));

        lblStart.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 245, 470, 50));

        lblNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 470, 50));

        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 170, 40));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah keberangkatan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateMouseClicked
        date.showPopup();
    }//GEN-LAST:event_btnDateMouseClicked

    private void cmbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMenuActionPerformed
             menu = String.valueOf(cmbMenu.getSelectedItem());
             System.out.println(menu);
cmbPaket.removeAllItems();   
                pakets.clear();
                               
             fillComboBox();
    }//GEN-LAST:event_cmbMenuActionPerformed

    private void cmbPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbPaketMouseClicked
//           String str = String.valueOf(cmbPaket.getSelectedItem());
//        String getId = str.substring( 0, str.indexOf(","));
//        int id = Integer.valueOf(getId);
//        System.out.println(id);
//        for(Paket pkt:paketRepo.getByid(id)){
//            System.out.println(pkt.getNama());
//        }
    }//GEN-LAST:event_cmbPaketMouseClicked

    private void cmbPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaketActionPerformed
           String str = String.valueOf(cmbPaket.getSelectedItem());
           try {
             String [] getId= str.split(",", 2);
        if(getId[0].equals(null)){
            getId[0] = String.valueOf(0);
        }
        int id = Integer.valueOf(getId[0]);
        System.out.println(id);
        for(Paket pkt:paketRepo.getByid(id)){
            lblNama.setText(pkt.getNama());
            lblStart.setText(pkt.getStart());
            lblDiskon.setText(String.valueOf(pkt.getDiskon()));
            lblDesc.setText(pkt.getDeskripsi());
            lblHarga.setText(String.valueOf(pkt.getHarga()));
            lblMinimDp.setText(String.valueOf(pkt.getMinimDp()));
            lblId.setText(String.valueOf(pkt.getId()));
        }
        } catch (Exception e) {
            
        }
       
    }//GEN-LAST:event_cmbPaketActionPerformed

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        
        try {
            int id = Integer.valueOf(lblId.getText());
        String tgl = txtDate.getText();
            Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
            Paket paket = new PaketRepository().get(id);
            String dateNow = dateUtil.dateNow();
            long diferent = dateUtil.subtractionTwoDate(dateNow, tgl);
            if(diferent > 0){
                String status = "Belum Berangkat";
            Keberangkatan keberangkatan = new Keberangkatan(paket, tanggal,status);
            boolean tambah = keberangkatanRepo.add(keberangkatan);
            if(tambah){
                System.out.println("berhasil");
                closeMessage();
            }else{
                System.out.println("gagal");
            }
                
            }else{
                System.out.println("tanggal sudah kelewat");
            }

        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_btnTambahMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnDate;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JComboBox<String> cmbMenu;
    private javax.swing.JComboBox<String> cmbPaket;
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMinimDp;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStart;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
