/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.PengeluaranOperasional;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import repository.PengeluaranOperasionalRepository;
import view.panel.PengeluaranForm;

/**
 *
 * @author adzaz
 */
public class DialogEditPengeluaranOperasional extends Dialog {
    private int id = PengeluaranForm.id;
    
    PengeluaranOperasionalRepository pengeluraeanOperasionalRepo = new PengeluaranOperasionalRepository();
    /**
     * Creates new form DialogEditPengeluaranOperasional
     */
    public DialogEditPengeluaranOperasional(JFrame fram) {
        super(fram);
        initComponents();
        setValue();
    }
    
    private void setValue(){
        for(PengeluaranOperasional res:pengeluraeanOperasionalRepo.getById(id)){
            txtNama.setText(res.getNamaPengeluaran());
            txtDesc.setText(res.getDeskripsi());
            txtDate.setText(res.getTanggal().toString());
            txtTotal.setText(String.valueOf(res.getJumlah()));
            lblId.setText(String.valueOf(res.getId()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new com.raven.datechooser.DateChooser();
        txtNama = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        btnDate = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();

        date.setTextRefernce(txtDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 155, 350, 40));

        txtTotal.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtTotal.setBorder(null);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 242, 350, 40));
        getContentPane().add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 280, 40));

        txtDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtDesc.setBorder(null);
        getContentPane().add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 433, 350, 40));

        btnDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDateMouseClicked(evt);
            }
        });
        getContentPane().add(btnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 50, 40));

        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 160, 40));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/edit pengeluaran.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDateMouseClicked
        date.showPopup();
    }//GEN-LAST:event_btnDateMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
            String nama = txtNama.getText();
            String desc = txtDesc.getText();
            int jumlah = Integer.parseInt(txtTotal.getText());
            String date = txtDate.getText();
            Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(date);
            PengeluaranOperasional pengeluaranRepo = new PengeluaranOperasional(nama, jumlah, tanggal, desc);
            pengeluaranRepo.setId(Integer.parseInt(lblId.getText()));
            boolean tambah = pengeluraeanOperasionalRepo.update(pengeluaranRepo);
            if(tambah){
                System.out.println("Berhasil di tambah");
                closeMessage();
            }else{
                System.out.println("gagal di tambah");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnDate;
    private javax.swing.JLabel btnTambah;
    private com.raven.datechooser.DateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
