/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;


import entity.Keberangkatan;
import entity.Pemesanan;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import repository.KeberangkatanRepository;
import repository.PaketRepository;
import repository.PemesananRepository;
import view.panel.KeberangkatanForm;

/**
 *
 * @author adzaz
 */
public class DialogDetailKeberangkatan extends Dialog {
    KeberangkatanRepository keberangkatanRepo = new KeberangkatanRepository();
    PaketRepository paketRepo = new PaketRepository();
    PemesananRepository pemesananRepo = new PemesananRepository();
    private int id = KeberangkatanForm.id;
    /**
     * Creates new form DialogDetailKeberangkatan
     */
    public DialogDetailKeberangkatan(JFrame fram) {
        super(fram);
        initComponents();
        loadTable();
        setInformasiPemesanan();
        setValue();
    }
    public void setInformasiPemesanan(){
        int jumlahJamaah = 0;
        int totalPemasukan = 0;
        int totalHarga = 0;
        int kekurangan = 0;
        for(Pemesanan pm:pemesananRepo.getByIdKeberangkatan(id)){
            jumlahJamaah += 1;
            totalPemasukan += pm.getJumlahBayar();
            totalHarga += pm.getTotalTagihan();
        }
        kekurangan = totalHarga - totalPemasukan;
        lblJmlJamaah.setText(String.valueOf(jumlahJamaah));
        lblTotalPemasukan.setText(String.valueOf(totalPemasukan));
        lblTotalHarga.setText(String.valueOf(totalHarga));
        lblKekurangan.setText(String.valueOf(kekurangan));
    }
    private void loadTable(){
       DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");      
            model.addColumn("Nama");
            model.addColumn("jenis pembayaran");
            model.addColumn("Status");
            model.addColumn("Jumlah bayar");

            int no = 1;
           
           for(Pemesanan res:pemesananRepo.getByIdKeberangkatan(id)){
                model.addRow(new Object[]{
                    no++,
                    res.getJamaah().getNama(),
                    res.getJenisPembayaran(),
                    res.getStatus(),
                    res.getJumlahBayar(), 
                });
           }
            table.setModel(model);
    }
    private void setValue(){
        for(Keberangkatan kb:keberangkatanRepo.getById(id)){
            lblId.setText(String.valueOf(kb.getId()));
            lblNama.setText(kb.getPaket().getNama());
            lblStart.setText(kb.getPaket().getStart());
            lblDesc.setText(kb.getPaket().getDeskripsi());
            lblHarga.setText(String.valueOf(kb.getPaket().getHarga()));
            lblDiskon.setText(String.valueOf(kb.getPaket().getDiskon()));
            lblMinimDp.setText(String.valueOf(kb.getPaket().getMinimDp()));
            lblTanggal.setText(kb.getTanggal().toString());
            lblMenu.setText(kb.getPaket().getMenu());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiskon = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        lblMinimDp = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblKekurangan = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        lblTotalPemasukan = new javax.swing.JLabel();
        lblJmlJamaah = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiskon.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 220, 40));

        lblHarga.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 220, 40));

        lblNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 227, 220, 40));

        lblDesc.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblDesc.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 313, 220, 40));

        lblMinimDp.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblMinimDp.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblMinimDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 220, 40));

        lblStart.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblStart.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 225, 220, 40));

        lblTanggal.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 186, 220, 40));

        lblKekurangan.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblKekurangan.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblKekurangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 220, 40));

        lblTotalHarga.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTotalHarga.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 220, 40));

        lblTotalPemasukan.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTotalPemasukan.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTotalPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 485, 220, 40));

        lblJmlJamaah.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblJmlJamaah.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblJmlJamaah, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 445, 220, 40));

        lblMenu.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 187, 220, 40));

        lblId.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 150, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 217, 400, 420));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/detail keberangkatan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1265, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        closeMessage();
    }//GEN-LAST:event_jLabel2MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblJmlJamaah;
    private javax.swing.JLabel lblKekurangan;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMinimDp;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblTotalPemasukan;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
