/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Paket;
import javax.swing.JFrame;
import repository.PaketRepository;

/**
 *
 * @author adzaz
 */
public class DialogTambahPaket extends Dialog {

    /**
     * Creates new form DialogTambahJamaah
     */
    public DialogTambahPaket(JFrame fram) {
        super(fram);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.ButtonGroup();
        Start = new javax.swing.ButtonGroup();
        txtDiskon = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtMinimDP = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesk = new javax.swing.JTextArea();
        rdUmroh = new javax.swing.JRadioButton();
        rdHaji = new javax.swing.JRadioButton();
        rdWisataHalal = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        rdJakarta = new javax.swing.JRadioButton();
        rdSurabaya = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiskon.setBorder(null);
        getContentPane().add(txtDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 240, 40));

        txtHarga.setBorder(null);
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 240, 40));

        txtMinimDP.setBorder(null);
        getContentPane().add(txtMinimDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 240, 40));

        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 290, 40));

        txtDesk.setColumns(20);
        txtDesk.setRows(5);
        txtDesk.setBorder(null);
        jScrollPane1.setViewportView(txtDesk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 690, 100));

        Menu.add(rdUmroh);
        rdUmroh.setText("umrah");
        rdUmroh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdUmrohActionPerformed(evt);
            }
        });
        getContentPane().add(rdUmroh, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 130, 20, 20));

        rdHaji.setText("haji");
        getContentPane().add(rdHaji, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 20, -1));

        rdWisataHalal.setText("wisata halal");
        getContentPane().add(rdWisataHalal, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 128, 20, -1));

        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 170, 40));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 170, 40));

        Start.add(rdJakarta);
        rdJakarta.setText("Surabaya");
        getContentPane().add(rdJakarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 127, 20, -1));

        Start.add(rdSurabaya);
        rdSurabaya.setText("Surabaya");
        getContentPane().add(rdSurabaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 128, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah paket.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdUmrohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdUmrohActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdUmrohActionPerformed

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        String nama = txtNama.getText();
        String desc = txtDesk.getText();
        int harga = Integer.valueOf(txtHarga.getText());
        int minimDp = Integer.valueOf(txtMinimDP.getText());
        int diskon = Integer.valueOf(txtDiskon.getText());
        String menu = null;
        String start = null;
        if(rdHaji.isSelected()){
            menu = "Haji";
        }else if(rdUmroh.isSelected()){
            menu = "Umrah";
        }else if(rdWisataHalal.isSelected()){
            menu = "Wisata Halal";
        }
        
        if(rdSurabaya.isSelected()){
            start = "Surabaya";
        }else if(rdJakarta.isSelected()){
            start = "Jakarta";
        }
        int lamaPaket = 9;
        Paket paket = new Paket(menu, start, nama, desc, minimDp, harga, diskon, lamaPaket);
        PaketRepository paketRepo = new PaketRepository();
        if(paketRepo.add(paket)){
            System.out.println("berhasil");
            closeMessage();
        }else{
            System.out.println("gagal");
        }
    }//GEN-LAST:event_btnTambahMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Menu;
    private javax.swing.ButtonGroup Start;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdHaji;
    private javax.swing.JRadioButton rdJakarta;
    private javax.swing.JRadioButton rdSurabaya;
    private javax.swing.JRadioButton rdUmroh;
    private javax.swing.JRadioButton rdWisataHalal;
    private javax.swing.JTextArea txtDesk;
    private javax.swing.JTextField txtDiskon;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtMinimDP;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
