/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.User;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import repository.UserRepository;

/**
 *
 * @author adzaz
 */
public class DialogTambahPegawai extends Dialog {
    private String fileName;
    UserRepository userRepo = new UserRepository();
    /**
     * Creates new form DialogTambahPegawai
     */
    public DialogTambahPegawai(JFrame fram) {
        super(fram);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtIdcard = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        btnTambahFoto = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 290, 40));

        txtUsername.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(0, 0, 0));
        txtUsername.setBorder(null);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 290, 40));

        txtIdcard.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtIdcard.setForeground(new java.awt.Color(0, 0, 0));
        txtIdcard.setBorder(null);
        getContentPane().add(txtIdcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 290, 50));

        txtAlamat.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtAlamat.setForeground(new java.awt.Color(0, 0, 0));
        txtAlamat.setBorder(null);
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 310, 290, 50));

        txtNotelp.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtNotelp.setForeground(new java.awt.Color(0, 0, 0));
        txtNotelp.setBorder(null);
        getContentPane().add(txtNotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 290, 50));

        txtNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtNama.setForeground(new java.awt.Color(0, 0, 0));
        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 290, 50));

        cmbJenisKelamin.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        cmbJenisKelamin.setForeground(new java.awt.Color(0, 0, 0));
        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));
        cmbJenisKelamin.setBorder(null);
        getContentPane().add(cmbJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 226, 300, 50));

        btnTambahFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahFotoMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambahFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 150, 30));

        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 610, 140, 30));

        lblId.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 290, 50));
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 135, 240, 305));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah pegawai.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 657));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahFotoMouseClicked
       if(txtUsername.getText().length() < 1){
           JOptionPane.showMessageDialog(null, "isi username terlebih dahulu");
       } else {
           try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(f.toString());
            Image img = icon.getImage().getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon ic = new ImageIcon(img);
            lblFoto.setIcon(ic);
            fileName = f.getAbsolutePath();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       }
       
    }//GEN-LAST:event_btnTambahFotoMouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        String nama = txtNama.getText();
        String idCard = txtIdcard.getText();
        String role = "employee";
        String pass = "12345678";
        String noTelp = txtNotelp.getText();
        String alamat = txtAlamat.getText();
        String username = txtUsername.getText();
        String email = txtEmail.getText();
        String jenisKelamin = String.valueOf(cmbJenisKelamin.getSelectedItem());
        try {
            String newpath = "src/upload";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdir();
            }
            File fileAwal = null;
            File fileAkhir = null;
            String ext = this.fileName.substring(fileName.lastIndexOf('.')+1);
            fileAwal = new File(fileName);
            fileAkhir = new File(newpath+"/"+txtUsername.getText()+"."+ext);
            System.out.println(fileAkhir);
            
            User user = new User(nama, username, role, pass, email, alamat, noTelp, fileAkhir.toString(), jenisKelamin, idCard);
            if(userRepo.add(user)){
                System.out.println("Berhasil");
                Files.copy(fileAwal.toPath(), fileAkhir.toPath());
                closeMessage();
            }else{
                System.out.println("gagal");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSimpanMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel btnTambahFoto;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdcard;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
