/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.dialog;

import entity.Barang;
import entity.DetailPengeluaran;
import entity.Keberangkatan;
import entity.Pemesanan;
import entity.Pengeluaran;
import javax.swing.JFrame;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import repository.BarangRepository;
import repository.DetailPengeluaranRepository;
import repository.KeberangkatanRepository;
import repository.PemesananRepository;
import repository.PengeluaranRepository;
import util.DateUtil;
import view.panel.PengeluaranForm;
/**
 *
 * @author adzaz
 */
public class DialogPengeluaranProduksi extends Dialog {
    private List<Barang> listBarang = new ArrayList<>();
    private int idKeberangkatan;
    private int idBarang = 0;
    private int StokB = 0;
    private int banyakOrang = 0;
    private int totalPemasukan = 0;
    private int grandTotal = 0;
    private int subHargaLainLain = 0;
    private int subHargaHotel = 0;
    private int subHargaPesawat = 0;
    private  int totalPengeluaranOpersional = 0;
    KeberangkatanRepository keberangkatanRepo = new KeberangkatanRepository();
    PemesananRepository pemesananRepo = new PemesananRepository();
    BarangRepository barangRepo = new BarangRepository();
    PengeluaranRepository pengeluaranRepo = new PengeluaranRepository();
    DetailPengeluaranRepository detailPengeluaranRepo = new DetailPengeluaranRepository();
    DateUtil date = new DateUtil();
    /**
     * Creates new form DialogPengeluaranProduksi
     */
    public DialogPengeluaranProduksi(JFrame fram) {
        super(fram);
        initComponents();
        setComboBoxBarang();
        loadTable();
        setTotalPengeluaran();
        setValue();
        setComboBoxPaket();
    }
    private void setComboBoxPaket(){
        for(Keberangkatan kb:keberangkatanRepo.getPemesananNull()){
            cmbPilihPaket.addItem(kb.getId() + ", " + kb.getPaket().getNama());
        }
    }
    private void loadTable(){
        try {
             DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");      
            model.addColumn("Nama");
            model.addColumn("Harga");
            model.addColumn("Jumlah");
            model.addColumn("Sub total");
            int no = 1;
           
           for(Barang res:listBarang){
                model.addRow(new Object[]{
                    no++,
                    res.getNama(),
                    res.getHarga(),
                    res.getStok(),
                    res.getSubTotal(),
                    
           });
            
    }
           table.setModel(model);
        } catch (Exception e) {
        }
    }
    private void setTotalPengeluaran(){
        try {
        totalPengeluaranOpersional = subHargaHotel + subHargaLainLain + subHargaPesawat + grandTotal;
        lblTotalPengeluaran.setText(String.valueOf(totalPengeluaranOpersional));

        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    private void setValue(){
        lblDate.setText(date.dateNow());
        try {
              for(Keberangkatan kb:keberangkatanRepo.getById(idKeberangkatan)){
           lblNama.setText(kb.getPaket().getNama());
           lblTanggal.setText(kb.getTanggal().toString());
        }
        int banyakOrg = 0;
        int ttlPemasukan = 0;
        for(Pemesanan pm:pemesananRepo.getByIdKeberangkatan(idKeberangkatan)){
            banyakOrg += 1;
            ttlPemasukan += pm.getJumlahBayar();
        }
        totalPemasukan = ttlPemasukan;
        banyakOrang = banyakOrg;
        lblBanyakOrang.setText(String.valueOf(banyakOrang));
        lblBanyakOrang1.setText(String.valueOf(banyakOrang));
        lblBanyakOrang2.setText(String.valueOf(banyakOrang));
        txtStok.setText(String.valueOf(banyakOrang));
        lblTotalPemasukan.setText(String.valueOf(totalPemasukan));
        } catch (Exception e) {
        }
    }
    
    private void setComboBoxBarang(){
          try {
             for(Barang jm:barangRepo.get()){
           cmbBarang.addItem(jm.getId()+","+jm.getNama()+", Stok = "+jm.getStok());
        }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLainLain = new javax.swing.JTextField();
        txtHargaHotel = new javax.swing.JTextField();
        txtPesawat = new javax.swing.JTextField();
        lblpengeluaranLainLain = new javax.swing.JLabel();
        lblPengeluaranHotel = new javax.swing.JLabel();
        lblHargaPesawat = new javax.swing.JLabel();
        lblTotalPengeluaran = new javax.swing.JLabel();
        lblTotalPemasukan = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblBanyakOrang2 = new javax.swing.JLabel();
        lblBanyakOrang1 = new javax.swing.JLabel();
        lblBanyakOrang = new javax.swing.JLabel();
        btnBatal = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cmbPilihPaket = new javax.swing.JComboBox<>();
        cmbBarang = new javax.swing.JComboBox<>();
        txtStok = new javax.swing.JTextField();
        btnTambahBarang = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLainLain.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtLainLain.setBorder(null);
        txtLainLain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLainLainKeyReleased(evt);
            }
        });
        getContentPane().add(txtLainLain, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 220, 40));

        txtHargaHotel.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtHargaHotel.setBorder(null);
        txtHargaHotel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHargaHotelKeyReleased(evt);
            }
        });
        getContentPane().add(txtHargaHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 220, 40));

        txtPesawat.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtPesawat.setBorder(null);
        txtPesawat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesawatKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 258, 220, 40));

        lblpengeluaranLainLain.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblpengeluaranLainLain.setForeground(new java.awt.Color(0, 0, 0));
        lblpengeluaranLainLain.setText("asd");
        getContentPane().add(lblpengeluaranLainLain, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 270, 40));

        lblPengeluaranHotel.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblPengeluaranHotel.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblPengeluaranHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 270, 50));

        lblHargaPesawat.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblHargaPesawat.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblHargaPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 270, 50));

        lblTotalPengeluaran.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTotalPengeluaran.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTotalPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 260, 40));

        lblTotalPemasukan.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTotalPemasukan.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTotalPemasukan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 260, 40));

        lblTanggal.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblTanggal.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 200, 50));

        lblNama.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 50));

        lblBanyakOrang2.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblBanyakOrang2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblBanyakOrang2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 50, 40));

        lblBanyakOrang1.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblBanyakOrang1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblBanyakOrang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 50, 40));

        lblBanyakOrang.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        lblBanyakOrang.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(lblBanyakOrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, 50));

        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 180, 40));

        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 170, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 420, 400));

        cmbPilihPaket.setBackground(new Color(0,0,0,0));
        cmbPilihPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilihPaketActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPilihPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 240, 50));

        cmbBarang.setBackground(new Color(0,0,0,0));
        cmbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBarangActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, 240, 50));

        txtStok.setFont(new java.awt.Font("Quicksand Bold", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        getContentPane().add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 164, 50, 30));

        btnTambahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahBarangMouseClicked(evt);
            }
        });
        getContentPane().add(btnTambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 160, 60, 50));

        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 670, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/image/tambah pengeluaran produksi.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 750));
        getContentPane().add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBarangActionPerformed
        
        try {
            String str = String.valueOf(cmbBarang.getSelectedItem());
            String [] getId= str.split(",", 5);
            String [] getStok = str.split("= ", 5);
            idBarang = Integer.valueOf(getId[0]);
            StokB = Integer.valueOf(getStok[1]);
        } catch (Exception e) {
            System.out.println("salah click");
            e.getMessage();
        }
        
    }//GEN-LAST:event_cmbBarangActionPerformed

    private void btnTambahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahBarangMouseClicked
        try {
            System.out.println(idBarang);
            System.out.println(StokB);
            int inputStok = Integer.parseInt(txtStok.getText());
            for(Barang br:barangRepo.getById(idBarang)){
                if(br.getStok() < inputStok){
                    System.out.println("stok tidak cukup");
                    return;
                }
                
                int subTotal = br.getHarga() * Integer.valueOf(txtStok.getText());
                
                listBarang.add(new Barang(br.getId(), br.getNama(), inputStok, br.getHarga(),subTotal));
            }
            int stotal = 0;
            for(Barang i:listBarang){
                stotal = i.getSubTotal();
            }
            grandTotal += stotal;
            setTotalPengeluaran();
            loadTable();
        } catch (Exception e) {
            System.out.println("salah tambah");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahBarangMouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        closeMessage();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        try {
            listBarang.clear();
       setTotalPengeluaran();
       loadTable();
       table.revalidate();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void txtPesawatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesawatKeyReleased
        int harga = Integer.parseInt(txtPesawat.getText());
         subHargaPesawat = harga * banyakOrang;
        lblHargaPesawat.setText(String.valueOf(subHargaPesawat));
        setTotalPengeluaran();
    }//GEN-LAST:event_txtPesawatKeyReleased

    private void txtHargaHotelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaHotelKeyReleased
        int harga = Integer.parseInt(txtHargaHotel.getText());
         subHargaHotel = harga * banyakOrang;
        lblPengeluaranHotel.setText(String.valueOf(subHargaHotel));
        setTotalPengeluaran();
    }//GEN-LAST:event_txtHargaHotelKeyReleased

    private void txtLainLainKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLainLainKeyReleased
        int harga = Integer.parseInt(txtLainLain.getText());
         subHargaLainLain = harga * banyakOrang;
        lblpengeluaranLainLain.setText(String.valueOf(subHargaLainLain));
        setTotalPengeluaran();
    }//GEN-LAST:event_txtLainLainKeyReleased

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
        if(totalPengeluaranOpersional >= totalPemasukan){
            System.out.println("bangkrut Cook!!!!");
        }else{
            String tgl = lblDate.getText();
        Date tanggal = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
        Keberangkatan keberangkatan = new KeberangkatanRepository().get(idKeberangkatan);
        Pengeluaran pengeluaran = new Pengeluaran(keberangkatan, tanggal, subHargaPesawat, subHargaHotel, subHargaLainLain, totalPengeluaranOpersional);
        boolean tambah = pengeluaranRepo.add(pengeluaran);
        
        if(tambah){
            System.out.println("Alhamdulillah iso");
            int idPengeluaran = 0;
            for(Pengeluaran p:pengeluaranRepo.getLastId()){
                idPengeluaran = p.getId();
            }
            for(Barang i:listBarang){
                Pengeluaran p = new PengeluaranRepository().get(idPengeluaran);
                Barang b = new BarangRepository().get(i.getId());
                DetailPengeluaran detailPengeluran = new DetailPengeluaran(
                        p, b, i.getStok(), i.getSubTotal());
                boolean tambahDetail = detailPengeluaranRepo.add(detailPengeluran);
                if(tambahDetail){
                    System.out.println("Allhamdulillah sukses");
                }else{
                    System.out.println("Gagal Teros marine kapan");
                }
            }
        }else{
            System.out.println("Eror terus Asuuuuu!!");
        }
        }
        } catch (Exception e) {
            System.out.println("Ojo eror teros babiii");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void cmbPilihPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilihPaketActionPerformed
        String str = String.valueOf(cmbPilihPaket.getSelectedItem());
        
        String[] getId = str.split(",",2);
        idKeberangkatan = Integer.parseInt(getId[0]);
        setValue();
    }//GEN-LAST:event_cmbPilihPaketActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel btnTambahBarang;
    private javax.swing.JComboBox<String> cmbBarang;
    private javax.swing.JComboBox<String> cmbPilihPaket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBanyakOrang;
    private javax.swing.JLabel lblBanyakOrang1;
    private javax.swing.JLabel lblBanyakOrang2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHargaPesawat;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblPengeluaranHotel;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotalPemasukan;
    private javax.swing.JLabel lblTotalPengeluaran;
    private javax.swing.JLabel lblpengeluaranLainLain;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtHargaHotel;
    private javax.swing.JTextField txtLainLain;
    private javax.swing.JTextField txtPesawat;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
